### ISSUE TITLE
Доступ к torrserve через https

### ISSUE THREAD

**Issue by minanov67** [vladlenas/Synology-TorrServer#12]
Использую torrserver на synology nas и смотрю на ios через nplayer со встроенным браузером (через родной интерфейс torrserve в dsm). До недавних пор все работало отлично, но теперь nplayer требует чтобы использовалось защищенное соединение. На самом nas установил сертификат и настроил подключение через https. Теперь могу зайти на основную страницу dsm через nplayer, но torrserve все еще использует http и не открывается. Соответственно, вопрос: можно ли сделать так, чтобы для доступа к torrserve тоже использовался https? Просто nplayer очень удобен для этих целей и я не уверен что есть достойная альтернатива.

**Comment by vladlenas** [comment]
Это возможно сделать через обратный прокси, портал для входа-дополнительно-обратный прокси. 
![Untitled](https://user-images.githubusercontent.com/54670862/137640939-35558593-c3ca-4452-9cb9-16b3f0a6ff40.jpg)
![Untitled1](https://user-images.githubusercontent.com/54670862/137640940-1e9eb70f-5ab8-40f3-86eb-97d7cbd880f8.jpg)

**Comment by vladlenas** [comment]
Но нужен домен рабочий, сертификат домена на Синолоджи, перенаправление днс. По локальному IP этого не сделать ....  
![Untitled2](https://user-images.githubusercontent.com/54670862/137641156-2d417fcf-30e5-494a-ab56-4369b2ade07c.jpg)

**Comment by minanov67** [comment]
Все получилось, все работает, спасибо большое!

**Comment by vladlenas** [comment]
Ну и отлично.
