### ISSUE TITLE
DSM 5.2 support

### ISSUE THREAD

**Issue by and7ey** [vladlenas/Synology-TorrServer#13]
Спасибо за проделанную работу!

Можно ли как-то установить torrserver на Synology DS210j? Это arm5, но последняя версия DSM для него - 5.2. 

При установке релиза 118-arm5, получаю сообщение This package doesn't contain a digital signature.

**Comment by vladlenas** [comment]
Добрый день, вручную если только. Для DSM 5 я не буду собирать.
