### ISSUE TITLE
DS218j не работают настройки кеширования.

### ISSUE THREAD

**Issue by khomenkov** [vladlenas/Synology-TorrServer#14]
на DS218j DSM 7.1.1-42962 Update 4 при любых настройках кеширования, кроме дефолтных, видео не воспроизводится - бесконечная загрузка данных. смотрю через длна.

**Comment by vladlenas** [comment]
Извиняюсь за столь поздний ответ, быстрее всего проблема в 512 МБ памяти. Ее просто не хватает для большего кеширования, лучше еще у меньшить кеш и смотреть не очень большие файлы.
