### ISSUE TITLE
Версия 124

### ISSUE THREAD

**Issue by JoyZzzzz** [vladlenas/Synology-TorrServer#15]
После установки версии TorrServer-6.0-MatriX.124-arm7.spk обновлением или как новая установка программа не работает. Ошибок при установке никаких не выдает. Откатился на 123 версию.

**Comment by vladlenas** [comment]
Добрый день,
слишком мало информации. Нужна модель Наса, версия DSM, ну и логи. Лог находится тут https://github.com/vladlenas/Synology-TorrServer#log-file
Можно из диспетчера задач вытянуть, запустить от root "cp /var/packages/TorrServer/target/config/TorrServer.log /volume1/шара" 
P.S. Быстрее всего будет не совместимость библиотек бинарника, так как я использую уже готовые, вам тогда лучше написать тут https://github.com/YouROK/TorrServer/issues

Но для начала, нужны логи.

**Comment by JoyZzzzz** [comment]
DS213j (MARVELL Armada 370) DSM 6.2.4-25556 Update 7
Судя по логу не стартует веб сервер. Ни автоматом, ни при ручном запуске.

Start without authorization
=========== START ===========
TorrServer MatriX.123, go1.20.3, CPU Num: 1
2023/06/05 22:04:36 UTC0 Check dns OK [209.85.233.99 209.85.233.147 209.85.233.106 209.85.233.105 209.85.233.104 209.85.233.103 2a00:1450:4010:c03::6a 2a00:1450:4010:c03::93 2a00:1450:4010:c03::63 2a00:1450:4010:c03::68] <nil>
2023/06/05 22:04:36 UTC0 Check web port 8090
2023/06/05 22:04:36 UTC0 Start TorrServer MatriX.123 torrent v1.49.1
2023/06/05 22:04:36 UTC0 Local IPs: [192.168.50.100]
2023/06/05 22:04:36 UTC0 Check listen port 32000
2023/06/05 22:04:36 UTC0 Set listen port 32000
2023/06/05 22:04:36 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/05 22:04:37 UTC0 PublicIp4: 89.*.*.*
2023/06/05 22:04:37 UTC0 Start web server at port 8090
Stop

Start without authorization
=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 1
2023/06/07 21:13:56 UTC0 Check dns OK [142.250.185.164 2a00:1450:4001:811::2004] <nil>
2023/06/07 21:13:56 UTC0 Check web port 8090
2023/06/07 21:13:56 UTC0 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/07 21:13:56 UTC0 Local IPs: [192.168.50.100]
2023/06/07 21:13:56 UTC0 Check listen port 32000
2023/06/07 21:13:56 UTC0 Set listen port 32000
2023/06/07 21:13:56 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/07 21:13:56 UTC0 PublicIp4: 89.*.*.*
Stop

Start without authorization
=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 1
2023/06/07 21:19:16 UTC0 Check dns OK [142.250.185.164 2a00:1450:4001:811::2004] <nil>
2023/06/07 21:19:16 UTC0 Check web port 8090
2023/06/07 21:19:16 UTC0 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/07 21:19:16 UTC0 Local IPs: [192.168.50.100]
2023/06/07 21:19:16 UTC0 Check listen port 32000
2023/06/07 21:19:16 UTC0 Set listen port 32000
2023/06/07 21:19:16 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/07 21:19:16 UTC0 PublicIp4: 89.*.*.*

**Comment by vladlenas** [comment]
Как я уже говорил, вам лучше обратиться  https://github.com/YouROK/TorrServer/issues. Структура пакета не менялась несколько лет, DSM 6 не обновляется около года. Если прошлая версия запускалась а эта нет, это почти 100% проблема самого бинарника  TorrServer. Как выше писал, я использую уже готовый (скомпелированный) бинарник.

**Comment by JoyZzzzz** [comment]
Круг замкнулся..

Может криво собрался spk? Можете попробовать его сделать по новой?

**Comment by vladlenas** [comment]
Ну я не против разобраться )
А как вы устанавливали? Через update или с выбором файла? Пробовали на чистую или поверх старой версии?

**Comment by JoyZzzzz** [comment]
Установка вручную -> выбор файла. 
Устанавливал и как апдейт на предыдущую версию и как новую установку. Перезагрузку nas тоже делал..  ;)

**Comment by vladlenas** [comment]
Понятно, осталось только запустить бинарник без всего обвеса. 
Я завтра или воскресенье, напишу инструкцию вам как запустить это. И попробуем запустить на другом порте веб.

**Comment by JoyZzzzz** [comment]
Попробовал запустить на xpenology на DSM7 TorrServer-7.0-MatriX.124-amd64.spk, там работает без проблем.
А так же предложило обновить на более новую версию 124,1 с китайского репо.

**Comment by vladlenas** [comment]
Ну так речь о Хрене, это совсем разные версии.  У меня же работает на amd64
бинарнике, а нам интересен arm7.

2023-06-09, pn 23:44, JoyZzzzz ***@***.***> rašė:

**Comment by JoyZzzzz** [comment]
Да, именно arm7 и на DSM6 не работает.

**Comment by vladlenas** [comment]
> Попробовал запустить на xpenology на DSM7 TorrServer-7.0-MatriX.124-amd64.spk, там работает без проблем. А так же предложило обновить на более новую версию 124,1 с китайского репо.

А что за китайское репо? Можно ссылку?

**Comment by JoyZzzzz** [comment]
На Xpenology прописан общий хаб https://synopackage.com/repository/spk/all
Но если не ошибаюсь апдейт тянуло с https://spk7.imnks.com

**Comment by vladlenas** [comment]
-качаем файл https://github.com/YouROK/TorrServer/releases/download/MatriX.124/TorrServer-linux-arm7
-положим например в /downloads (вы можете разместить куда хотите, просто поменяйте /downloads на свою директорию)
-Панель управления-Планировщик задач-Создать-Запущенная задача-Скрипт, заданный пользователем
На первой странице дать название и пользователь root, на второй странице вставить скрипт
`cd /volume1/downloads
chmod +x TorrServer-linux-arm7
./TorrServer-linux-arm7 -p 8091 -d /volume1/downloads/ -l /volume1/downloads/log & exit`
-Запустить задачу
-Если все хорошо, будет доступен по ip_nas:8091. Порт я специально прописал не дефолтный, лог будет в /downloads или там где у вас лежит сам бинарник.

**Comment by vladlenas** [comment]
Остановить, создать такую же задачу, только с другим скриптом
 `killall TorrServer-linux-arm7`

**Comment by JoyZzzzz** [comment]
Не устанавливается.
Попробовал 123 скачать, тоже не ставиться.

**Comment by vladlenas** [comment]
> Не устанавливается. Попробовал 123 скачать, тоже не ставиться.

Значит ошибка в скрипте где то. Можно включить логи диспетчера, будет понятно где ошибка.
![Screenshot 2023-06-10 214604](https://github.com/vladlenas/Synology-TorrServer/assets/54670862/cdf6ab4a-082f-4723-8c06-d4f491b87523)

**Comment by JoyZzzzz** [comment]
в script.log указывается запускаемая команда
в output.log пусто

**Comment by vladlenas** [comment]
> в script.log указывается запускаемая команда в output.log пусто

Тогда все хорошо, запустилось без ошибок.

**Comment by vladlenas** [comment]
В директории где лежит TorrServer файл, появляются файлы config.db и log?

**Comment by JoyZzzzz** [comment]
нет файлов

**Comment by vladlenas** [comment]
> нет файлов

тогда что то делаете не так

**Comment by JoyZzzzz** [comment]
может в телеграмм перейдем ?

**Comment by vladlenas** [comment]
> может в телеграмм перейдем ?

Зачем? Не вижу смысла .....

**Comment by JoyZzzzz** [comment]
Тогда а что может быть не так выполняться? Запуск делал так как вы написали. Так же пробовал запускать через ssh. Результат тот же. 

В какую директорию вообще устанавливается программа ?

**Comment by vladlenas** [comment]
> Тогда а что может быть не так выполняться? Запуск делал так как вы написали. Так же пробовал запускать через ssh. Результат тот же.

В том, что мой пакет тут не причем. Скрипты на всех версиях одинаковые, если amd64 запускается а arm7 нет, то вывод же очевидный. Я не разработчик TorrServer, поэтому не вижу смысла дальше продолжать.

**Comment by vladlenas** [comment]
> В какую директорию вообще устанавливается программа ?

/volume1/@appstore/TorrServer/bin/

**Comment by JoyZzzzz** [comment]
Такая папка не создается при запуске скриптом

**Comment by JoyZzzzz** [comment]
Если скрипт выполнять по отдельности. то зависает на:

user@NAS:/volume1/tmp/124$ ./TorrServer-linux-arm7 -p 8091 -d /volume1/tmp/124/ -l /volume1/tmp/124/log
2023/06/12 00:03:10 ffprobe and avprobe not found in $PATH

**Comment by vladlenas** [comment]
> 2023/06/12 00:03:10 ffprobe and avprobe not found in $PATH

Стартует и сразу падает, это строчка самая первая в логе.

**Comment by JoyZzzzz** [comment]
Оно висит пока ctrl+с не нажать 
Попробовал версию 123 и 120 все аналогично при запуске этой командой

**Comment by JoyZzzzz** [comment]
Или ssh команда или скрипт начали работать.
Появился файл log и config.db

=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 1
2023/06/11 21:07:57 UTC0 Check dns OK [142.250.203.132 2a00:1450:401b:80e::2004] <nil>
2023/06/11 21:07:57 UTC0 Check web port 8091
2023/06/11 21:07:57 UTC0 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/11 21:07:57 UTC0 Local IPs: [192.168.50.100]
2023/06/11 21:07:57 UTC0 Check listen port 32000
2023/06/11 21:07:57 UTC0 Set listen port 32000
2023/06/11 21:07:57 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/11 21:07:57 UTC0 PublicIp4: 89.*.*.*

**Comment by JoyZzzzz** [comment]
> -d /volume1/downloads/ -l 
В скрипте из-за / в пути скрипт не отрабатывался.

**Comment by JoyZzzzz** [comment]
120 и 123 версия стартуют нормально
124 так же не запускает web server

**Comment by vladlenas** [comment]
> Как я уже говорил, вам лучше обратиться https://github.com/YouROK/TorrServer/issues. Структура пакета не менялась несколько лет, DSM 6 не обновляется около года. Если прошлая версия запускалась а эта нет, это почти 100% проблема самого бинарника TorrServer. Как выше писал, я использую уже готовый (скомпелированный) бинарник.

Я в самом начале писал же, что сам пакет тут не причем. Теперь уже понятно на 100%, что проблема в самом бинарнике.
