### ISSUE TITLE
Authorization doesn't work dsm 7.2

### ISSUE THREAD

**Issue by rrmt23** [vladlenas/Synology-TorrServer#16]
Hi
In the latest version of the package that I installed on DSM 7.2 - Authorisation does not work. 
During installation I checked the box, but when I go to ip:8090 I still end up without an authorisation request.

Check please. 

Thank you!

**Comment by rrmt23** [comment]
Приветствую!

При установке пакета ставлю галочку, чтобы была авторизация.
Но после установки без запрса учетных данных свободно попадаю по ip:8090.

NAS Synology 7.2 920+, 126 версия amd64.

**Comment by vladlenas** [comment]
[https://github.com/vladlenas/Synology-TorrServer/commit/64d12ffcc23e279e3d1168326aa0ff649b06bc61](url)

**Comment by vladlenas** [comment]
https://github.com/vladlenas/Synology-TorrServer/commit/64d12ffcc23e279e3d1168326aa0ff649b06bc61
