### ISSUE TITLE
Автоперезапуск при падении

### ISSUE THREAD

**Issue by TheChief5055** [vladlenas/Synology-TorrServer#2]
Как-то можно это сделать?

**Comment by vladlenas** [comment]
Можно, но может лучше понять почему падает?
Какой у вас Нас?
Какая версия DSM?
Какая версия Торрсервера у вас падает? Или с любой версией происходит падение?

**Comment by vladlenas** [comment]
![1](https://user-images.githubusercontent.com/54670862/127272296-227db55e-8b35-4a45-8a2b-c5a7f78a24a6.jpg)
![2](https://user-images.githubusercontent.com/54670862/127272299-1098d339-067f-40a3-a15f-1f067fd0a94a.jpg)
![3](https://user-images.githubusercontent.com/54670862/127272301-b55c0d74-93d8-4b61-8f15-47e4da0ef8d6.jpg)

`pidof TorrServer >/dev/null ; [[ $? -ne 0 ]] && sudo synopkg start TorrServer &`

**Comment by TheChief5055** [comment]
> Можно, но может лучше понять почему падает?
> Какой у вас Нас?
> Какая версия DSM?
> Какая версия Торрсервера у вас падает? Или с любой версией происходит падение?

DS918+ / 8Гб памяти. В настройках задан 320Мб буфер, 32Мб предзагрузка. Падает при остановке воспроизведения и попытке воспроизведения другого торрента (клиент — VPlay на телевизоре).

**Comment by vladlenas** [comment]
> > Можно, но может лучше понять почему падает?
> > Какой у вас Нас?
> > Какая версия DSM?
> > Какая версия Торрсервера у вас падает? Или с любой версией происходит падение?
> 
> DS918+ / 8Гб памяти. В настройках задан 320Мб буфер, 32Мб предзагрузка. Падает при остановке воспроизведения и попытке воспроизведения другого торрента (клиент — VPlay на телевизоре).

У меня 720+, нет таких проблем с Торрсервером. Попробуйте с Андроид клиентом, быстрее всего VPlay так себя ведет с торрсервером.

**Comment by vladlenas** [comment]
closed
