### ISSUE TITLE
Media Station X

### ISSUE THREAD

**Issue by JoyZzzzz** [vladlenas/Synology-TorrServer#6]
Don't want to build with Media Station X support?
https://github.com/kolsys/TorrServer

**Comment by vladlenas** [comment]
> Don't want to build with Media Station X support?
> https://github.com/kolsys/TorrServer

https://github.com/vladlenas/Synology-TorrServer/releases/tag/Synology-TorrSrver-MatriX.105-1

**Comment by vladlenas** [comment]
https://github.com/vladlenas/Synology-TorrServer/commit/4ca2e64df99aa9dc38fcfdd5955ad108b1999033
